
name: Docker build and publish image
on: 
  push:
    tags: 
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      
    - name: Check out code into the directory
      uses: actions/checkout@v2
      
    - name: Prepare
      id: prep
      run: |
        DOCKER_IMAGE=wlanboy/mariadb-arm32v7
        VERSION=latest
        echo ::set-output name=tags::${VERSION}
        echo ::set-output name=docker_image::${DOCKER_IMAGE}
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@master
      with:
        platforms: all
        
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Publish to Registry
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: ./Dockerfile
        platforms: linux/arm32v7
        push: true
        tags: ${{ steps.prep.outputs.tags }}
